#!/bin/bash
echo "🧪 Dashboard Testing - Quick Start"
echo "=================================="
echo ""
echo "📋 Prerequisites:"
echo "1. Backend running: npm start (in BackEnd folder)"
echo "2. Frontend running: npm run dev (in FrontEnd folder)"
echo "3. PostgreSQL running"
echo ""
echo "🚀 Quick Test:"
echo "1. Run backend test:"
echo "   cd BackEnd && node test-login-dashboard.js"
echo ""
echo "2. Open browser: http://localhost:5173"
echo ""
echo "3. Login with:"
echo "   Email: dashboardtest@pharmacy.com"
echo "   Password: test12345"
echo ""
echo "4. Go to Dashboard and check:"
echo "   ✓ F12 → Console for logs"
echo "   ✓ Application → LocalStorage for token"
echo "   ✓ Network tab for API calls"
echo ""
echo "5. Expected results:"
echo "   - Total Orders: 3"
echo "   - Active Medications: 3"
echo "   - Refill Alerts: 0"
echo "   - AI Interactions: 0"
echo ""
echo "📝 See DASHBOARD_TESTING_GUIDE.md for detailed instructions"
